### ISSUE TITLE
[feature request] provide close method to close the zookeeper handle and the session.

### ISSUE THREAD

**Issue by yjqg6666** [php-zookeeper/php-zookeeper#12]
Providing a  wrapper to **ZOOAPI int zookeeper_close(zhandle_t *zh)** is appreciated.
The destructor method for freeing up resources is missing. 
Now we could only unset the client object. Would the zookeeper handle be closed and end the zookeeper session?

**Comment by Timandes** [comment]
If we actually provide the method `close()`, what behavior do you expect when calling some method like `get()` after closing?

```
<?php
$zookeeper = new Zookeeper('localhost:2181');
$r = $zookeeper->get('/path');
var_dump($r);
$zookeeper->close();

$r = $zookeeper->get('/path');// ???
?>
```

**Comment by jsteggink** [comment]
For me, throwing an exception would be prefered. The same holds when a path doesn't exist. What do you think about this?

**Comment by Timandes** [comment]
Sorry for waiting.
Would you please try c0295fa22e5fd5ec637cadf31133cb560acdde1e of branch 'close'?

**Comment by yjqg6666** [comment]
Sorry for the delayed response. I just tried and it works well. Thanks.
