### ISSUE TITLE
Drop PHP5 support?

### ISSUE THREAD

**Issue by jbboehr** [php-zookeeper/php-zookeeper#14]
Should we drop PHP5 support?

**Comment by Timandes** [comment]
Sorry to answer it late.
What remind you to call this operation? :)

**Comment by Timandes** [comment]
@jbboehr Are you still interested in this issue?
I'll create a new branch in order to implement possible future fixes in PHP5.
Then we can do the job in master branch.
Do you agree these steps? Or you have other ideas?
: )

**Comment by Timandes** [comment]
Future release '0.5.x'  will be the last version which supports PHP 5.x.

**Comment by Auvipev** [comment]
I think versions that the php community still supports is what this repository should support. For example PHP 5.6, 7.0, 7.1, and 7.2 are all still supported and so we should at least support PHP 5.6 and up. That is my opinion.

**Comment by Timandes** [comment]
I agree.
So we will still maintain the series 0.5.x for bug fix. New features would not be added to this branch.

**Comment by Timandes** [comment]
Branch `zend-engine-3` is in progress now.

**Comment by Timandes** [comment]
Release 0.7.0 is done for this issue.
