### ISSUE TITLE
PHP 7.2 Support

### ISSUE THREAD

**Issue by michaelgrosser** [php-zookeeper/php-zookeeper#16]
Is there a time table for PHP 7.2 support? The pecl version of the module caps support at php 7.1.99.

**Comment by jbboehr** [comment]
The tests are passing already on 7.2 I believe, so we just need to publish a new release that whitelists 7.2. You can install it the traditional way in the meantime.

**Comment by Timandes** [comment]
Updated.
f32aa8206160ba5239b582d771dcf9881627baa5
: )
