### ISSUE TITLE
[warning] php_zookeeper.c in function 'php_zk_completion_marshal

### ISSUE THREAD

**Issue by LockGit** [php-zookeeper/php-zookeeper#18]
`
/usr/local/src/php-zookeeper/php_zookeeper.c: In function 'php_zk_completion_marshal':
/usr/local/src/php-zookeeper/php_zookeeper.c:1144:27: warning: initialization discards 'const' qualifier from pointer target type [enabled by default]
  php_cb_data_t *cb_data = context;
                           ^
/usr/local/src/php-zookeeper/php_zookeeper.c:1157:13: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
  p->cb_data = context;
             ^
`

version info:
zookeeper-3.4.10
PHP 7.0.20

**Comment by Timandes** [comment]
Could you try php-zookeeper@b11a258 ?

**Comment by LockGit** [comment]
@Timandes Wonderful , every thing is fine ! Thanks
