### ISSUE TITLE
support connect zookeeper cluster ?

### ISSUE THREAD

**Issue by LockGit** [php-zookeeper/php-zookeeper#20]
example,have three zookeeper server, It's  a zookeeper cluster, below code doesn't work:
`
 $connectStr = 'host1:2181,host2:2181,host3:2181';

 $zc = new \Zookeeper($connectStr);

var_export($zc->get('xxx/xx'));
`

**Comment by Timandes** [comment]
So it emitted some exception or just output an empty value?
Could you provide me some version infos?

**Comment by LockGit** [comment]
I solved the problem，client connect zookeeper server is asynchronous , so I use another way solved this question:



```php
class ZkClient {
    private $zk;
    private function __construct() {
        $connectStr = 'host1:2181,host2:2181,host3:2181';
        $zk = new \Zookeeper($connectStr);
        $i = 0;
        //client connect zookeeper cluster avoid invalid zookeeper server
        while ($zk->getState() !== 3) {
            usleep(500);
            if ($i > 100) {
                break;
            }
            $i++;
        }
        $this->zk = $zk;
        if ($this->zk == null) {
            throw new Exception('connect zookeeper cluster fail');
        }
    }
}
```

**Comment by GaneshChandrasekaran-zz** [comment]
I am going raise some similar concerns in the same thread as I am experiencing the issue as well. Let's say I have a cluster of 3 servers, if I am doing maintenance on 1 of the servers then I am still getting a `Failed to connect to Zookeeper` message from `ZookeeperConnectionException`. If I have a cluster running shouldn't it be able to tolerate failure of 1 node in an ensemble of 3 servers?

@Timandes let me know if I should open a new issue for this discussion.

**Comment by Timandes** [comment]
Sorry for my late reply.
I have the same concern, too. So would you do me a favour to start a new issue so that we can continue to discus it?
Thank you very much.

**Comment by GaneshChandrasekaran-zz** [comment]
Done -> https://github.com/php-zookeeper/php-zookeeper/issues/29
