### ISSUE TITLE
undefined symbol: zoo_wgetconfig

### ISSUE THREAD

**Issue by remicollet** [php-zookeeper/php-zookeeper#22]
Buld time:

```
/dev/shm/BUILD/php-pecl-zookeeper-0.6.0/ZTS/php_zookeeper_config_class.c: In function 'zim_ZookeeperConfig_get':
/dev/shm/BUILD/php-pecl-zookeeper-0.6.0/ZTS/php_zookeeper_config_class.c:82:14: warning: implicit declaration of function 'zoo_wgetconfig'; did you mean 'zoo_wget'? [-Wimplicit-function-declaration]
     status = zoo_wgetconfig(i_obj->php_zk->zk, (fci.size != 0) ? php_zk_watcher_marshal : NULL,
              ^~~~~~~~~~~~~~
              zoo_wget
/dev/shm/BUILD/php-pecl-zookeeper-0.6.0/ZTS/php_zookeeper_config_class.c: In function 'php_zookeeper_config_reconfig_impl':
/dev/shm/BUILD/php-pecl-zookeeper-0.6.0/ZTS/php_zookeeper_config_class.c:274:14: warning: implicit declaration of function 'zoo_reconfig'; did you mean 'zoo_htonll'? [-Wimplicit-function-declaration]
     status = zoo_reconfig(i_obj->php_zk->zk, joining, leaving, members, version, buffer, &buffer_len, &stat);
              ^~~~~~~~~~~~
              zoo_htonll

```

Please document minimal version required, and add a check in config.m4 for these symbols

**Comment by Timandes** [comment]
Fixed in 0.6.1.
Thank you for your report.

**Comment by remicollet** [comment]
Sorry, but still unfixed

```
+ /usr/bin/php --no-php-ini --define extension=modules/zookeeper.so --modules
PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/zookeeper.so' - modules/zookeeper.so: undefined symbol: zoo_wgetconfig in Unknown on line 0

```

**Comment by Timandes** [comment]
Thanks. I’ll check it ASAP.
But it’s weird.
I’m confused about it anyway.
Could you provide a bit more information so that I can try to figure it out?
:)

**Comment by remicollet** [comment]
Probably because I build against version **3.4.9** available in Fedora
https://apps.fedoraproject.org/packages/zookeeper

(I don't see such function in the library headers)

Also note that PHP is build with RTLD_NOW (instead of RTLD_LAZY) which means missing symbols are reported immediately at launch time (instead of segfault later, at runtime, when needed)

I see 2 possible way:
* make new methods conditional (on library version)
* document and check minimal required version in config.m4

**Comment by omega13a** [comment]
zoo_wgetconfig doesn't appear to exist in zookeeper 3.4.x. It only appears in version 3.5.x which is isn't stable yet.

**Comment by Timandes** [comment]
That’s right.
I said it’s weird because of this: I have dealt with that condition by using #ifdef. And it seams that there is no this issue in compiled version of libzookeeper.
I’m working on it now. If you have any idea please let us know.:)

**Comment by omega13a** [comment]
I've been trying to fix the problem myself and it seems that if you want to have this compatible with zookeeper 3.4.x, you'll need to include code from zookeeper 3.5.x because there doesn't appear to be 3.4.x equivalents for all the new functions in 3.5.x. I'm still trying to figure out what parts of the code need to be included...

**Comment by Timandes** [comment]
Thank you for your effort anyway. 👍

**Comment by Timandes** [comment]
I've fixed this issue in master branch.
Would you like to try that?
@remicollet @omega13a

**Comment by remicollet** [comment]
Seems OK:
```

$ php -n -d extension=modules/zookeeper.so --ri zookeeper

zookeeper

zookeeper support => enabled
version => 0.6.1
libzookeeper version => 3.4.9

```

**Comment by Timandes** [comment]
Thank you.:)
