### ISSUE TITLE
https://pecl.php.net/package/zookeeper 0.6.1 not update to lastest version，make fail

### ISSUE THREAD

**Issue by iyangyi** [php-zookeeper/php-zookeeper#24]
download from `https://pecl.php.net/package/zookeeper` 0.6.1 。have not update to the lastest version。

so ,will bring  following error：

```
make && make install
```
error:

```
duplicate symbol _php_zk_config_ce in:
    .libs/php_zookeeper.o
    .libs/php_zookeeper_config_class.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [zookeeper.la] Error 1
```

but, I change download form  `github master version` ,it success。

so ,please update `pecl` to the lastest github master version。thank you。

**Comment by Timandes** [comment]
OK.
Thank you for your report.
I’m waiting for further response of issue#22.
After that, i’ll update it ASAP.

**Comment by iyangyi** [comment]
👍

**Comment by ghost** [comment]
link failed too

```
ext/zookeeper/.libs/php_zookeeper_config_class.o: In function `zim_ZookeeperConfig_get':
php_zookeeper_config_class.c:(.text+0x253): undefined reference to `zoo_wgetconfig'
ext/zookeeper/.libs/php_zookeeper_config_class.o: In function `php_zookeeper_config_reconfig_impl':
php_zookeeper_config_class.c:(.text+0xa9b): undefined reference to `zoo_reconfig'
collect2: error: ld returned 1 exit status
make: *** [sapi/cli/php] Error 1
make: *** Waiting for unfinished jobs....
ext/zookeeper/.libs/php_zookeeper_config_class.o: In function `zim_ZookeeperConfig_get':
php_zookeeper_config_class.c:(.text+0x253): undefined reference to `zoo_wgetconfig'
ext/zookeeper/.libs/php_zookeeper_config_class.o: In function `php_zookeeper_config_reconfig_impl':
php_zookeeper_config_class.c:(.text+0xa9b): undefined reference to `zoo_reconfig'
collect2: error: ld returned 1 exit status
make: *** [sapi/fpm/php-fpm] Error 1

```

version 3.4.13

**Comment by ghost** [comment]
3.5.4 is good

**Comment by Timandes** [comment]
@di3663
Could you try master branch?

**Comment by ghost** [comment]
yes, master branch and last release are the same.

ps: php-fpm itself whose version bigger than 7.2.7 are all broken.

**Comment by ghost** [comment]
@Timandes

**Comment by Timandes** [comment]
@di3663
Could you provide your full configure parameters and other infos such as OS and PHP?

**Comment by ghost** [comment]
ok: centos7 x64, php 7.2.7 nts x64, zookeeper 3.5.4, php-zookeeper 0.6.2
not ok: zookeeper 3.4.*

@Timandes

**Comment by Timandes** [comment]
I built a VM and tested it.
It worked fine.
This is my ENV parameters:
```
# php -v
PHP 7.2.8 (cli) (built: Jul 17 2018 09:50:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

# uname -a
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```

And this is my commands:
```
yum groupinstall "Development Tools"

tar xvf zookeeper-3.4.12.tar.gz
cd zookeeper-3.4.12
./configure --prefix=/usr/local/libzookeeper-3.4.12
make install
cd ..

tar xvf zookeeper-0.6.2.tgz
cd zookeeper-0.6.2
phpize
./configure --with-libzookeeper-dir=/usr/local/libzookeeper-3.4.12
make
```

**Comment by ghost** [comment]
@Timandes

Do not know why, but following is the command. 
I build zookeeper as a static module because people said that static module has better performance.

ldconfig -v

PATH=/opt/autoconf/bin:$PATH ./buildconf --force
PKG_CONFIG_PATH=%PKG_CONFIG_PATH%:/opt/freetype2/lib/pkgconfig CC=gcc CXX=g++ CFLAGS="-P -fPIC" ./configure --prefix=/usr --sysconfdir=/etc/php --sbindir=/usr/bin --enable-mbstring --disable-debug --enable-cli --enable-embed=static --disable-cgi --enable-fpm --disable-phpdbg --enable-redis=static --with-pdo-mysql --with-gd --with-freetype-dir=/opt/freetype2 --with-openssl=/opt/openssl/usr/local/ssl --with-openssl-dir=/opt/openssl/usr/local/ssl --with-jpeg-dir=/opt/libjpeg --with-curl --with-zlib --enable-bcmath --enable-zip --enable-ftp --enable-calendar --enable-exif --enable-intl --enable-soap --enable-sockets --enable-zookeeper=static --with-libzookeeper-dir=/opt/zookeeper

```
php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
intl
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib
zookeeper

[Zend Modules]
```

**Comment by Timandes** [comment]
I moved zookeeper source dir to php-7.2.7/ext/zookeeper, and tried to compile it as you described.
But I got a warning, and it seems like not working at all:
```
configure: WARNING: unrecognized options: --enable-zookeeper, --with-libzookeeper-dir
```

So I still need more details.
