### ISSUE TITLE
Support for installing zookeeper extension for travis build

### ISSUE THREAD

**Issue by GaneshChandrasekaran-zz** [php-zookeeper/php-zookeeper#25]
Hello,

I am working on a project that is writing some functional tests for an application using zookeeper. I am trying to install the zookeeper extension and libzookeeper to run those tests.

I was wondering if I could get some help on passing the `libzookeeper-dir` during `configure`...

The failure message: 
https://travis-ci.org/symfony/symfony/jobs/410575167

The` travis.yml` changes that I am trying to make this work:
https://github.com/symfony/symfony/pull/27920/files

**Comment by Timandes** [comment]
After `zookeeper-3.4.12.tar.gz` decompressed, you should compile the C source code in directory `src/c` with:
```
./configure --prefix=/path/to/libzookeeper
make
make install
```

So the real `libzookeeper-dir` is `/path/to/libzookeeper`.

**Comment by GaneshChandrasekaran-zz** [comment]
All set here, thanks.
