### ISSUE TITLE
compiled from sources doesnt work

### ISSUE THREAD

**Issue by prograamer** [php-zookeeper/php-zookeeper#26]
Hi

zookeeper.so has been installed from sources  without any errors

php -m

/usr/lib64/php/modules/zookeeper.so: undefined symbol: php_zk_config_register

any suggestions ?

php version 7.2.9

Thanks

**Comment by Timandes** [comment]
Could you provide system info, ZooKeeper version and version of your extension?

**Comment by prograamer** [comment]
I've built them from sources (master branch)

system: Centos 7 with latest updates.

**Comment by Timandes** [comment]
What about system and ZooKeeper?

**Comment by prograamer** [comment]
Zookeeper built from master too
