### ISSUE TITLE
Zookeeper connection resiliency

### ISSUE THREAD

**Issue by GaneshChandrasekaran-zz** [php-zookeeper/php-zookeeper#29]
Based on this setup: https://zookeeper.apache.org/doc/r3.3.3/zookeeperAdmin.html#sc_zkMulitServerSetup

Let's say I have a cluster of 3 servers, if I am doing maintenance on 1 of the servers then I am still getting a Failed to connect to Zookeeper message from ZookeeperConnectionException. If I have a cluster running shouldn't it be able to tolerate failure of 1 node in an ensemble of 3 servers?

**Comment by GaneshChandrasekaran** [comment]
Related to this I also am not sure why the constructor establishes a session asynchronously. What is the use case for it?
http://php.net/manual/en/zookeeper.construct.php

Shouldn't this be synchronous? I know Java docs does this asynchronously as well and these rely on callback functions to take corresponding actions. But how does making it asynchronous help?

**Comment by Timandes** [comment]
Sorry for my late reply.

I've read related source files belonged to ZooKeeper C Client, and read what you wrote twice.

At first, I thought it was related to "Fail to connect". So I was looking for errors related "connection" and got CONNECTION_LOSS.
Suddenly i realized that the way C Client connecting to server is asynchronous. `ZooKeeper::connect()` and constructor do not actually connect to it.

After that, i reviewed `php_zookeeper_connect_impl()` and finally got the answer:

When `zookeeper_init()` returns NULL, we will throw an exception "Failed to connect to Zookeeper". But actually it means "Failed to intiailize ZooKeeper Client"!

According to `zookeeper_init_internal()`, when these events happen, `zookeeper_init` will return 0(equals to NULL):
- `calloc(1, sizeof(*zh));` fails.
- `Win32WSAStartup()` fails (#ifdef _WIN32).
