### ISSUE TITLE
Segmentation fault after destroying Zookeeper instance

### ISSUE THREAD

**Issue by BaDos** [php-zookeeper/php-zookeeper#32]
# Description
I faced Segmentation fault after destroying the Zookeeper instance.
I have created a small app to reproduce this issue: https://github.com/BaDos/ZookeeperSegmentationFault

# Steps to reproduce
* Clone repo
* Run `composer install`
* Run `php test.php app:test`

## Expected result
In ErrorHandler.php line 48:
Notice: Undefined offset: 3 in /Users/bohdan/Sites/console-test/src/TestCommand.php on line 28

## Actual result
[1]    14737 segmentation fault  php test.php app:test

# Reproduced on
* PHP version: 7.1.15, 7.1.26, 7.2.15
* OS: MacOS, Linux
* Zookeeper version: 0.6.3, 0.7.0

**Comment by Timandes** [comment]
Interesting.

**Comment by Timandes** [comment]
https://bugs.php.net/bug.php?id=77692

**Comment by Timandes** [comment]
Would you try the master branch again?
I think I've solved this issue with help of PHP fellows. : )

**Comment by BaDos** [comment]
@Timandes I have tested the compiled extension from the master branch.
Looks like it works fine 🎉 
Thanks for the quick fix.
When do you plan to release it?

**Comment by Timandes** [comment]
Now?
: )
