### ISSUE TITLE
在swoole中watch不生效

### ISSUE THREAD

**Issue by idrunk** [php-zookeeper/php-zookeeper#33]
```php
swoole_async_set(array(
    'enable_reuse_port' => true,
    'enable_signalfd' => false, // See: https://github.com/swoole/swoole-src/issues/302
));

$serv = new Swoole\Server("0.0.0.0", 9502, SWOOLE_BASE);

$serv->set(array(
    'worker_num' => 1,
));

$serv->on('Receive', function (swoole_server $serv, $fd, $from_id, $data)
{
    $serv->send($fd, "Swoole: " . $data);
});

function recursive_listen(Zookeeper $zk_php, $path_nerve) {
    $zk_php->get($path_nerve, function ($i, $type, $key) use ($zk_php) {
        $zk_php->get($key, null, $stat);
        var_dump($i, $type, $key, $stat/*, $zk_php->get($path_nerve)*/);
        recursive_listen($zk_php, $key);
    });
}

$serv->on('WorkerStart', function ($serv, $worker_id)
{
    var_dump('start');

    $path_nerve = '/millet/service_redis_redis_config';

    $zk_php = new Zookeeper('zoo1:2181,zoo2:2181,zoo3:2181');

    recursive_listen($zk_php, $path_nerve);

  // 不加入这个循环就无法监听, 加入了才有监听
    while (1) {
        sleep(1);
    }

});

$serv->start();
```

上述代码中, 如果删掉while块, 则set时不会进入get的watcher, 必须加上那个while卡在那, set时才能触发watch, 不知道什么原因, 还是我用得不对, 望指点

- php 7.3.2
- php_zookeeper 0.6.3
- swoole 4.2.13

**Comment by Timandes** [comment]
因为线程数据同步原因，目前这个扩展使用`zend_interrupt_function`触发ZooKeeper的回调事件。
如果直接使用Swoole内部的调度机制，`zend_interrupt_function`没有机会工作，也就无法触发ZooKeeper的回调事件。
本人能力有限，暂无办法直接解决这个问题。
可以尝试在`$serv->on('WorkerStart'`的回调函数中加入如下代码段代替`while(1)`：
```php
swoole_timer_tick(100, function() {
  zookeeper_dispatch();
});
```
每隔100ms主动轮询一次ZooKeeper的待处理回调时间清单。

**Comment by idrunk** [comment]
> 因为线程数据同步原因，目前这个扩展使用`zend_interrupt_function`触发ZooKeeper的回调事件。
> 如果直接使用Swoole内部的调度机制，`zend_interrupt_function`没有机会工作，也就无法触发ZooKeeper的回调事件。
> 本人能力有限，暂无办法直接解决这个问题。
> 可以尝试在`$serv->on('WorkerStart'`的回调函数中加入如下代码段代替`while(1)`：
> 
> ```
> swoole_timer_tick(100, function() {
>   zookeeper_dispatch();
> });
> ```
> 
> 每隔100ms主动轮询一次ZooKeeper的待处理回调时间清单。

非常感谢回复, 我在swoole的issues也发了这个问题, 作者回复我新开一个进程跑zookeeper, 我考虑下用什么方法
