### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by dtakken** [php-zookeeper/php-zookeeper#34]
Hello,

Would it be possible to extend support to PHP 7.3? Currently, the pecl version of the module caps support at php 7.2.99.

**Comment by Timandes** [comment]
> Release 0.7.1: | PHP Version: PHP version 7.4.99 or olderPHP Version: PHP 7.0.0 or newerPEAR Package: PEAR 1.4.0b1 or newer

????

**Comment by dtakken** [comment]
My apologies. My install script only considered stable versions and failed saying PHP 7.3 is not supported. I was too fast to draw conclusions. The script has been adjusted and it installs fine now.

Thanks anyways for your quick response!
