### ISSUE TITLE
PHP 7.4 Installation Steps

### ISSUE THREAD

**Issue by meow-watermelon** [php-zookeeper/php-zookeeper#47]
Hi,

This is not an issue request. I figured out the steps to install PHP-ZooKeeper in PHP 7.4 from the source code so would like to share the steps here: https://github.com/meow-watermelon/EOSS/blob/main/notes/php-zookeeper-install.md

Hope this helps users who encounter the installation issue.

Thanks.

**Comment by zhupeijie** [comment]
您好，邮件已收到，我近期会登录查看，祝您天天开心！
