### ISSUE TITLE
Compile error with php-8.0.9 enable ZTS

### ISSUE THREAD

**Issue by serverglen** [php-zookeeper/php-zookeeper#49]
PHP Version：8.0.9  enable-zts
GCC Version：8.2.0
Zookeeper Version：3.4.10
php-zookeeper Version：1.0.0

compile error：
/home/php8.0/zookeeper/src/php_zookeeper.c: In function 'php_zk_watcher_marshal':
/home/php8.0/zookeeper/src/php_zookeeper.c:986:57: error: expected expression before ';' token
  void *prev = tsrm_set_interpreter_context(cb_data->ctx);
                                                         ^
/home/php8.0/zookeeper/src/php_zookeeper.c: In function 'php_zk_completion_marshal':
/home/php8.0/zookeeper/src/php_zookeeper.c:1032:57: error: expected expression before ';' token
  void *prev = tsrm_set_interpreter_context(cb_data->ctx);

**Comment by serverglen** [comment]
looks like was fixed by https://github.com/php-zookeeper/php-zookeeper/commit/25aa2db175691a34a83003776220e7c3c083666e

**Comment by parallels999** [comment]
if it was already solved it should be closed

**Comment by parallels999** [comment]
Fix already released
