### ISSUE TITLE
New Pecl Release

### ISSUE THREAD

**Issue by johnpbloch** [php-zookeeper/php-zookeeper#52]
Thanks for continuing to maintain this extension! Would it be possible to get a new version packaged on pecl.php.net for installation from the pecl repository on PHP 8.1 installations? Thanks!

**Comment by zhupeijie** [comment]
您好，邮件已收到，我近期会登录查看，祝您天天开心！

**Comment by parallels999** [comment]
Also PHP 8.2 is already here, It seems that this is how we will get to PHP 8.3

**Comment by dmitryuk** [comment]
@Timandes please make a new RECL release

**Comment by mlocati** [comment]
This issue can be closed, isn't it? Version 1.2.0 (and 1.2.1) is now on PECL! Thanks!

**Comment by parallels999** [comment]
Already released

**Comment by zhupeijie** [comment]
您好，邮件已收到，我近期会登录查看，祝您天天开心！
