### ISSUE TITLE
How to install from pecl?

### ISSUE THREAD

**Issue by simPod** [php-zookeeper/php-zookeeper#59]
`pecl install zookeeper-1.2.1`

> checking for libzookeeper location... configure: error: zookeeper support requires libzookeeper. Use --with-libzookeeper-dir=<DIR> to specify the prefix where libzookeeper headers and library are located

Is there a guide how to install from pecl?

**Comment by zhupeijie** [comment]
您好，邮件已收到，我近期会登录查看，祝您天天开心！

**Comment by faabiosr** [comment]
@simPod I don't know if you handle the installation, but first you need to install the zookeeper-client and after run the `pecl`.

More info on how to install the `zookeeper-client` in https://github.com/php-zookeeper/php-zookeeper/blob/master/scripts/zk-client-install.sh#L25-L34
